### ISSUE TITLE
UpTempo violates the GPL

### ISSUE THREAD

**Issue by ashimokawa** [vssh/pebble-upTempo#1]
You have to release the source code, as your code is based on On11, which is licensed under the terms of the GPL.

https://github.com/heqian/On11/blob/master/LICENSE

**Comment by vssh** [comment]
Yes, I was trying to finalise the code before checking it in. But is taking longer than I expected.
You are right, I will clean up the code and check it in.

**Comment by tecufanujacu** [comment]
@vssh 
Thanks alot, publishing the code I think that you will also have some help by an other great developer as @ashimokawa because there also is the interest in integrating your watchapp with GadgetBridge:
https://github.com/Freeyourgadget/Gadgetbridge/issues/316

**Comment by ashimokawa** [comment]
@vssh 
Thanks, definitely looking forward to that.
Well - you had a year to publish the source code, so it is overdue. I can understand that it might be embarrassing to publish dirty source code though. But in this case the rules are quite clear.

I decided to contact you as there is interest to support UpTempo natively in Gadgetbridge, but I refused to support it without having the source code.

**Comment by vssh** [comment]
@ashimokawa 
I appreciate the interest, but I do dislike the way that you went about it insinuating that I did not want  to publish the code.
The app is still in beta and though it has been over a year, there have been several large updates to the app and publishing code each time as a lone developer takes time that I would rather use to improve the app. I know the rules and the license, but blindly following rules would not be very useful if the app itself remains unusable. That is the reason why it says beta in the store listing and was never publicized; it is not completely ready for public consumption.
Anyway, it is nearly there and the code will be released as soon as I finish code cleanup(within a week, I expect).

I also took a look at Gadgetbridge, and it looks very cool. But I do not know how you plan to integrate UpTempo it. Does Gadgetbridge have its own UI for health data? I saw how you integrate Misfit and others but UpTempo structures data a bit differently, so it might be a bit more work. The easiest solution would be just to forward the data to UpTempo android app. If you don't want to do that(I don't know if the android app will be open source), I can help you correctly interpret and display data received from the watchapp.

@tecufanujacu 
Thanks for the encouragement, glad you like the app.

**Comment by vssh** [comment]
Closed it accidentally, will close it when code is released.

**Comment by tecufanujacu** [comment]
GadgetBridge has its own UI for health data as you can see here:
https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-System-Apps
and for this would be great use this watchapp without an Android companion app.

About the watchapp would be great have the ability to set the sensibility, what do you think about this setting?
