### ISSUE TITLE
Feature request: add support for the client GadgetBridge

### ISSUE THREAD

**Issue by tecufanujacu** [vssh/pebble-upTempo#2]
Unfortunately the android companion app isn't able to communicate with its watchapp via GadgetBridge.

I hope that you'll support GadgetBridge, after Pebble bankrupt a lot of people are moving on it as you can see in [#451](https://github.com/Freeyourgadget/Gadgetbridge/issues/451).

**Comment by vssh** [comment]
It should already work with GadgetBridge. I, actually, tested it myself for a bit and I could get it to work somewhat. But, GadgetBridge seems to lose connection with the watch quite a bit, so I could not test extensively.
Anyway, GadgetBridge is supposed to be compliant with the Pebble API and upTempo works well with the Pebble app. So, I suppose any bugs are with the Gadgetbridge's implementation of PebbleKit API. Please check if GadgetBridge implements the complete PebbleKit API, and that the implementation is stable. You may raise an issue with them, if you find any bugs.
Another problem might be that you might need to uninstall Pebble app completely. Also try installing GadgetBridge before upTempo Android app.

**Comment by tecufanujacu** [comment]
That's strange, from the android app I receive the message: "Communication unsuccessful. Do you have the latest version of upTempo watchapp?"

I have the watchapp v0.25 and the companion app v 0.0.12-beta.

Obviously I'm using GadgetBridge from several months and I installed the Android companion app only yesterday.
What should I do?

**Comment by vssh** [comment]
Turn on GadgetBridge Settings > pebble Settings > Allow 3rd party Android app access. It is aparently experimental, so it would seem the feature is not stable.

**Comment by tecufanujacu** [comment]
Hello, I already did, I retried more times and starts working but I uninstalled everything because I haven't understood how they work. 
If I only use the wathapp it works correctly but when I use the watchapp with the companion app then I don't have any data in the watchapp and in the companion app, for example when I walk I see 0 steps on the watchapp and I don't have any data on the phone.

**Comment by vssh** [comment]
This is probably because the implementation from GadgetBridge is still experimental. I hope it will improve with time. Please raise an issue with them.
I will close this issue here since it is not relevant to upTempo, but if you need support you can email me on the developer email anytime.

**Comment by ashimokawa** [comment]
@tecufanujacu 
@vssh 
Indeed it is because you use datalogging. Even though that makes sense, no one did that before ;)
So it is our fault (Gadgetbridge)

**Comment by vssh** [comment]
@ashimokawa thanks for informing us on the issue. Feel free to contact me, if you need any assistance testing the watchapp side of datalogging implementation.
@tecufanujacu thanks for bringing the issue to our attention. Hopefully, it gets resolved soon.

**Comment by tecufanujacu** [comment]
Hello @vssh , thanks to @ashimokawa this problem has been solved in GadgetBridge and I'm testing your app and I can tell you that its interface is really amazing.
I have a question, have you never think to collaborate in the GadgetBridge development? your help would be wonderfull, just now there is the issue [#301](https://github.com/Freeyourgadget/Gadgetbridge/issues/301) in which you could help really a lot.
