### ISSUE TITLE
Feature request: flexible idle alert

### ISSUE THREAD

**Issue by devilj** [vssh/pebble-upTempo#3]
i believe it will be cool to be able to have a little more flexibility on idle alerts:
- configure what is considered non-idleness, be it a number of steps taken or minimal amount of time spent active to reset the timer.
- be able to set alert for less than 1 hour. i would love to be reminded every 30 minutes.

**Comment by vssh** [comment]
I'm sorry but the Pebble watchapp is considered stable, and I am not considering adding any new features. Only bugfixes from now on.
